import {
  Code,
  Network,
  Blocks,
  Package,
  FileText,
  GitBranch,
  Cpu,
  type LucideIcon,
} from "lucide-react";
import type { SignalCategory } from "./signal-graph-data";

export const CATEGORY_ICONS: Record<SignalCategory, LucideIcon> = {
  code: Code,
  api: Network,
  architecture: Blocks,
  dependency: Package,
  documentation: FileText,
  workflow: GitBranch,
  agent: Cpu,
};

export const CATEGORY_LABELS: Record<SignalCategory, string> = {
  code: "Code Signals",
  api: "API & Interface Signals",
  architecture: "Architecture Signals",
  dependency: "Dependency & Infrastructure Signals",
  documentation: "Documentation Signals",
  workflow: "Repository / Workflow Signals",
  agent: "Agent / System Signals",
};

export const CATEGORY_SHORT_LABELS: Record<SignalCategory, string> = {
  code: "Code",
  api: "API & Interface",
  architecture: "Architecture",
  dependency: "Dependency",
  documentation: "Documentation",
  workflow: "Workflow",
  agent: "Agent / System",
};

export const CATEGORY_SUBTITLES: Record<SignalCategory, string> = {
  code: "Something in the code changed",
  api: "Components communicate changed",
  architecture: "System structure changed",
  dependency: "Environment depends changed",
  documentation: "Suggests docs may be stale",
  workflow: "Development workflow happened",
  agent: "Generated by AutoScribe itself",
};
