"""add llm fields to architecture tables

Revision ID: 120e7dd6d3fc
Revises: bbad9d8fbedd
Create Date: 2026-08-13 14:03:37.048451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '120e7dd6d3fc'
down_revision: Union[str, None] = 'bbad9d8fbedd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('architecture_edges', sa.Column('label', sa.String(), nullable=False))
    op.add_column('architecture_edges', sa.Column('traffic', sa.Float(), nullable=False))
    op.add_column('architecture_edges', sa.Column('kind', sa.String(), nullable=False))
    op.add_column('architecture_nodes', sa.Column('short', sa.String(), nullable=False))
    op.add_column('architecture_nodes', sa.Column('purpose', sa.String(), nullable=False))
    op.add_column('architecture_nodes', sa.Column('doing', sa.String(), nullable=False))
    op.add_column('architecture_nodes', sa.Column('health', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('architecture_nodes', 'health')
    op.drop_column('architecture_nodes', 'doing')
    op.drop_column('architecture_nodes', 'purpose')
    op.drop_column('architecture_nodes', 'short')
    op.drop_column('architecture_edges', 'kind')
    op.drop_column('architecture_edges', 'traffic')
    op.drop_column('architecture_edges', 'label')
    # ### end Alembic commands ###
