"""add sample_files to analyses

Revision ID: bbad9d8fbedd
Revises: d05e98a49fa1
Create Date: 2026-08-13 13:30:01.086679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbad9d8fbedd'
down_revision: Union[str, None] = 'd05e98a49fa1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('sample_files', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analyses', 'sample_files')
    # ### end Alembic commands ###
