"""add github_repo_id to repositories

Revision ID: d05e98a49fa1
Revises: 9d6e861fd2ae
Create Date: 2026-08-12 23:47:16.992635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd05e98a49fa1'
down_revision: Union[str, None] = '9d6e861fd2ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column('github_repo_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repositories', 'github_repo_id')
    # ### end Alembic commands ###
