"""Add title to ChatConversation

Revision ID: d42a8f1d46b3
Revises: b8d4a1c6e9f0
Create Date: 2026-09-01 13:45:35.792379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd42a8f1d46b3'
down_revision: Union[str, None] = 'b8d4a1c6e9f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_conversations', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_conversations', 'title')
    # ### end Alembic commands ###
