/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as CompleteRouteImport } from './routes/complete'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AnalyzingRouteImport } from './routes/analyzing'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppRepositoriesRouteImport } from './routes/_app.repositories'
import { Route as AppPullRequestsRouteImport } from './routes/_app.pull-requests'
import { Route as AppDocumentsLogRouteImport } from './routes/_app.documents-log'
import { Route as AppDocumentationRouteImport } from './routes/_app.documentation'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppAskRouteImport } from './routes/_app.ask'
import { Route as AppArchitectureRouteImport } from './routes/_app.architecture'
import { Route as AppRepositoryIdRouteImport } from './routes/_app.repository.$id'

const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const CompleteRoute = CompleteRouteImport.update({
  id: '/complete',
  path: '/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzingRoute = AnalyzingRouteImport.update({
  id: '/analyzing',
  path: '/analyzing',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRepositoriesRoute = AppRepositoriesRouteImport.update({
  id: '/repositories',
  path: '/repositories',
  getParentRoute: () => AppRoute,
} as any)
const AppPullRequestsRoute = AppPullRequestsRouteImport.update({
  id: '/pull-requests',
  path: '/pull-requests',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsLogRoute = AppDocumentsLogRouteImport.update({
  id: '/documents-log',
  path: '/documents-log',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentationRoute = AppDocumentationRouteImport.update({
  id: '/documentation',
  path: '/documentation',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAskRoute = AppAskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => AppRoute,
} as any)
const AppArchitectureRoute = AppArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => AppRoute,
} as any)
const AppRepositoryIdRoute = AppRepositoryIdRouteImport.update({
  id: '/repository/$id',
  path: '/repository/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analyzing': typeof AnalyzingRoute
  '/auth': typeof AuthRoute
  '/complete': typeof CompleteRoute
  '/connect': typeof ConnectRoute
  '/architecture': typeof AppArchitectureRoute
  '/ask': typeof AppAskRoute
  '/dashboard': typeof AppDashboardRoute
  '/documentation': typeof AppDocumentationRoute
  '/documents-log': typeof AppDocumentsLogRoute
  '/pull-requests': typeof AppPullRequestsRoute
  '/repositories': typeof AppRepositoriesRoute
  '/settings': typeof AppSettingsRoute
  '/repository/$id': typeof AppRepositoryIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analyzing': typeof AnalyzingRoute
  '/auth': typeof AuthRoute
  '/complete': typeof CompleteRoute
  '/connect': typeof ConnectRoute
  '/architecture': typeof AppArchitectureRoute
  '/ask': typeof AppAskRoute
  '/dashboard': typeof AppDashboardRoute
  '/documentation': typeof AppDocumentationRoute
  '/documents-log': typeof AppDocumentsLogRoute
  '/pull-requests': typeof AppPullRequestsRoute
  '/repositories': typeof AppRepositoriesRoute
  '/settings': typeof AppSettingsRoute
  '/repository/$id': typeof AppRepositoryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/analyzing': typeof AnalyzingRoute
  '/auth': typeof AuthRoute
  '/complete': typeof CompleteRoute
  '/connect': typeof ConnectRoute
  '/_app/architecture': typeof AppArchitectureRoute
  '/_app/ask': typeof AppAskRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/documentation': typeof AppDocumentationRoute
  '/_app/documents-log': typeof AppDocumentsLogRoute
  '/_app/pull-requests': typeof AppPullRequestsRoute
  '/_app/repositories': typeof AppRepositoriesRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/repository/$id': typeof AppRepositoryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analyzing'
    | '/auth'
    | '/complete'
    | '/connect'
    | '/architecture'
    | '/ask'
    | '/dashboard'
    | '/documentation'
    | '/documents-log'
    | '/pull-requests'
    | '/repositories'
    | '/settings'
    | '/repository/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analyzing'
    | '/auth'
    | '/complete'
    | '/connect'
    | '/architecture'
    | '/ask'
    | '/dashboard'
    | '/documentation'
    | '/documents-log'
    | '/pull-requests'
    | '/repositories'
    | '/settings'
    | '/repository/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/analyzing'
    | '/auth'
    | '/complete'
    | '/connect'
    | '/_app/architecture'
    | '/_app/ask'
    | '/_app/dashboard'
    | '/_app/documentation'
    | '/_app/documents-log'
    | '/_app/pull-requests'
    | '/_app/repositories'
    | '/_app/settings'
    | '/_app/repository/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AnalyzingRoute: typeof AnalyzingRoute
  AuthRoute: typeof AuthRoute
  CompleteRoute: typeof CompleteRoute
  ConnectRoute: typeof ConnectRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complete': {
      id: '/complete'
      path: '/complete'
      fullPath: '/complete'
      preLoaderRoute: typeof CompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyzing': {
      id: '/analyzing'
      path: '/analyzing'
      fullPath: '/analyzing'
      preLoaderRoute: typeof AnalyzingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/repositories': {
      id: '/_app/repositories'
      path: '/repositories'
      fullPath: '/repositories'
      preLoaderRoute: typeof AppRepositoriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pull-requests': {
      id: '/_app/pull-requests'
      path: '/pull-requests'
      fullPath: '/pull-requests'
      preLoaderRoute: typeof AppPullRequestsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documents-log': {
      id: '/_app/documents-log'
      path: '/documents-log'
      fullPath: '/documents-log'
      preLoaderRoute: typeof AppDocumentsLogRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documentation': {
      id: '/_app/documentation'
      path: '/documentation'
      fullPath: '/documentation'
      preLoaderRoute: typeof AppDocumentationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ask': {
      id: '/_app/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AppAskRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/architecture': {
      id: '/_app/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof AppArchitectureRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/repository/$id': {
      id: '/_app/repository/$id'
      path: '/repository/$id'
      fullPath: '/repository/$id'
      preLoaderRoute: typeof AppRepositoryIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppArchitectureRoute: typeof AppArchitectureRoute
  AppAskRoute: typeof AppAskRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDocumentationRoute: typeof AppDocumentationRoute
  AppDocumentsLogRoute: typeof AppDocumentsLogRoute
  AppPullRequestsRoute: typeof AppPullRequestsRoute
  AppRepositoriesRoute: typeof AppRepositoriesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppRepositoryIdRoute: typeof AppRepositoryIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppArchitectureRoute: AppArchitectureRoute,
  AppAskRoute: AppAskRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDocumentationRoute: AppDocumentationRoute,
  AppDocumentsLogRoute: AppDocumentsLogRoute,
  AppPullRequestsRoute: AppPullRequestsRoute,
  AppRepositoriesRoute: AppRepositoriesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppRepositoryIdRoute: AppRepositoryIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AnalyzingRoute: AnalyzingRoute,
  AuthRoute: AuthRoute,
  CompleteRoute: CompleteRoute,
  ConnectRoute: ConnectRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
