import json
from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session as DBSession

from app.api.auth import get_current_user
from app.core.security import decrypt_token
from app.db.session import get_db
from app.models import User, GithubAccount, Repository, RepoSettings, PullRequest, Document, DocumentVersion, ActivityLog
from app.services.writeback import write_back_docs

router = APIRouter(prefix="/api", tags=["pull-requests"])


def _owned_repo(repo_id: int, user: User, db: DBSession) -> Repository:
    repo = db.query(Repository).filter(Repository.id == repo_id, Repository.user_id == user.id).first()
    if not repo:
        raise HTTPException(status_code=404, detail="Repository not found")
    return repo


@router.get("/pull-requests")
def list_pull_requests(user: User = Depends(get_current_user), db: DBSession = Depends(get_db)):
    repos = db.query(Repository).filter(Repository.user_id == user.id).all()
    repos_by_id = {r.id: r for r in repos}
    if not repos_by_id:
        return []

    prs = (
        db.query(PullRequest)
        .filter(PullRequest.repository_id.in_(repos_by_id.keys()))
        .order_by(PullRequest.id.desc())
        .all()
    )

    return [
        {
            "id": str(pr.id),
            "repoId": str(pr.repository_id),
            "repoName": repos_by_id[pr.repository_id].name,
            "number": pr.github_pr_number,
            "title": pr.title,
            "branch": pr.branch,
            "status": pr.status,
            "createdAt": pr.created_at.isoformat(),
        }
        for pr in prs
    ]


@router.post("/repos/{repo_id}/sync-pr")
def sync_pull_request(repo_id: int, user: User = Depends(get_current_user), db: DBSession = Depends(get_db)):
    repo = _owned_repo(repo_id, user, db)
    account = db.query(GithubAccount).filter(GithubAccount.user_id == user.id).first()
    if not account:
        raise HTTPException(status_code=400, detail="No GitHub account connected")
    token = decrypt_token(account.access_token_encrypted)

    repo_settings = db.query(RepoSettings).filter(RepoSettings.repository_id == repo.id).first()

    # Get latest readme version data
    doc = db.query(Document).filter(Document.repository_id == repo.id, Document.slug == "readme").first()
    latest_version = (
        db.query(DocumentVersion)
        .filter(DocumentVersion.document_id == doc.id)
        .order_by(DocumentVersion.id.desc())
        .first()
        if doc else None
    )

    if latest_version:
        try:
            readme_data = json.loads(latest_version.content)
        except json.JSONDecodeError:
            readme_data = {"title": repo.name, "tagline": "", "overview": latest_version.content, "features": [], "quick_start": "", "architecture": ""}
    else:
        readme_data = {
            "title": repo.name,
            "tagline": "Repository documentation",
            "overview": "Documentation generated by AutoScribe.",
            "features": ["Automated Architecture Mapping", "Living Documentation"],
            "quick_start": "npm install\nnpm run dev",
            "architecture": "Modular architecture.",
        }

    try:
        writeback_result = write_back_docs(token, repo, repo_settings, readme_data)
        pr_info = writeback_result.get("pr", {})
        pr_number = pr_info.get("number", 1)

        existing_pr = (
            db.query(PullRequest)
            .filter(
                PullRequest.repository_id == repo.id,
                PullRequest.github_pr_number == pr_number,
            )
            .first()
        )
        if not existing_pr:
            existing_pr = PullRequest(
                repository_id=repo.id,
                github_pr_number=pr_number,
                title=pr_info.get("title", f"docs: sync README ({repo.name})"),
                branch=writeback_result.get("branch", "docs/autoscribe"),
                status="open",
            )
            db.add(existing_pr)
            db.flush()

        db.add(ActivityLog(
            repository_id=repo.id,
            text=f"Opened PR #{pr_number}: {existing_pr.title}"[:180],
            type="pr",
        ))

        repo.open_prs = (
            db.query(PullRequest)
            .filter(PullRequest.repository_id == repo.id, PullRequest.status == "open")
            .count()
        )
        db.commit()

        return {
            "status": "success",
            "mode": writeback_result.get("mode", "pr"),
            "prNumber": pr_number,
            "prUrl": f"https://github.com/{repo.org}/{repo.name}/pull/{pr_number}",
            "title": existing_pr.title,
            "branch": existing_pr.branch,
        }
    except Exception as exc:
        db.rollback()
        raise HTTPException(status_code=500, detail=f"Failed to create PR: {str(exc)}")